# org 기준 잘되는 거 2936, 3845
org :
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 #  73233
  dlg:
    iter : 300
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client:
    epoch : 300
    noise_level : 0
    precision : float32
#############################
vggnet :
  model : vggnet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 #  73233
  dlg:
    iter : 300
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client:
    epoch : 300
    noise_level : 0
    precision : float32

resnet :
  model : resnet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 #  73233
  dlg:
    iter : 300
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client:
    epoch : 300
    noise_level : 0
    precision : float32

ffn :
  model : ffn
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 #  73233
  dlg:
    iter : 300
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client:
    epoch : 300
    noise_level : 0
    precision : float32

#############################
batch_2 : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 2
    idx : 3845 # 245
  dlg: 
    iter : 600
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client: 
    epoch : 1
    noise_level : 0
    precision : float32

batch_4 : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 4
    idx : 3845 # 245
  dlg: 
    iter : 600
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client: 
    epoch : 1
    noise_level : 0
    precision : float32

batch_8 : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 8
    idx : 3845 # 245
  dlg: 
    iter : 600
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client: 
    epoch : 1
    noise_level : 0
    precision : float32

batch_16 : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 16
    idx : 3845 # 245
  dlg: 
    iter : 600
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client: 
    epoch : 1
    noise_level : 0
    precision : float32

#############################
optim_Adam : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 # 245
  dlg: 
    iter : 50000
    lr : 1e-2
    optim : Adam
    precision : float32
    has_label : False
  client: 
    epoch : 1
    noise_level : 0
    precision : float32

optim_AdamW : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 # 6243
  dlg: 
    iter : 50000
    lr : 1e-2
    optim : AdamW
    precision : float32
    has_label : False
  client: 
    epoch : 1
    noise_level : 0
    precision : float32

optim_SGD : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 # 245
  dlg: 
    iter : 50000
    lr : 1e-2
    optim : SGD
    precision : float32
    has_label : False
  client: 
    epoch : 1
    noise_level : 0
    precision : float32

##############################
noise_1 : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 # 245
  dlg: 
    iter : 300
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client: 
    epoch : 1
    noise_level : 1
    precision : float32

noise_2 : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 # 245
  dlg: 
    iter : 300
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client: 
    epoch : 1
    noise_level : 2
    precision : float32

noise_3 : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 # 245
  dlg: 
    iter : 300
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client: 
    epoch : 1
    noise_level : 3
    precision : float32

##############################
have_label : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 # 245
  dlg: 
    iter : 300
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : True
  client: 
    epoch : 1
    noise_level : 0
    precision : float32

##############################
quant_64_64 : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 # 245
  dlg: 
    iter : 300
    lr : 1
    optim : LBFGS
    precision : float64
    has_label : False
  client: 
    epoch : 1
    noise_level : 0
    precision : float64

quant_16_16 : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 # 245
  dlg: 
    iter : 300
    lr : 1
    optim : LBFGS
    precision : float16
    has_label : False
  client: 
    epoch : 1
    noise_level : 0
    precision : float16

#################################
iter_100 : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 # 245
  dlg: 
    iter : 100
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client: 
    epoch : 1
    noise_level : 0
    precision : float32

iter_200 : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 # 245
  dlg: 
    iter : 200
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client: 
    epoch : 1
    noise_level : 0
    precision : float32

iter_400 : 
  model : lenet
  data : 
    dataset : CIFAR100
    batch_size : 1
    idx : 3845 # 245
  dlg: 
    iter : 400
    lr : 1
    optim : LBFGS
    precision : float32
    has_label : False
  client: 
    epoch : 1
    noise_level : 0
    precision : float32